"""
ExecutiveReport Beanie MongoDB Document — Phase 11 Milestone 2.

Stores the final consolidated executive sales report generated by ExecutiveAgent
at the end of each successful 6-agent business pipeline run.
"""
from datetime import datetime, timezone
from typing import Dict, List, Optional, Any
from beanie import Document, PydanticObjectId
from pydantic import Field


class ExecutiveReport(Document):
    """Final consolidated executive sales report produced by ExecutiveAgent."""

    report_id: str = Field(..., description="Unique report identifier")
    job_id: str = Field(..., description="Associated AgentJob ID")
    lead_id: Optional[PydanticObjectId] = None
    owner_id: PydanticObjectId
    goal: str = Field(..., description="Original user goal submitted to agent runtime")
    company_name: str = Field(..., description="Target company name")

    # Executive Summary
    executive_summary: str = Field(default="", description="3-5 sentence executive opportunity summary")
    opportunity_score: int = Field(0, ge=0, le=100, description="Overall opportunity score 0-100")

    # Sales Playbook
    sales_playbook: Dict[str, Any] = Field(default_factory=dict, description="4-phase sales playbook")

    # Strategy
    top_pain_points: List[str] = Field(default_factory=list)
    winning_value_proposition: str = Field(default="")
    key_differentiators: List[str] = Field(default_factory=list)

    # Risk Assessment
    risk_assessment: List[Dict[str, Any]] = Field(default_factory=list, description="List of risks with severity and mitigation")

    # Action Items
    recommended_actions: List[Dict[str, Any]] = Field(default_factory=list, description="Prioritized recommended actions")
    execution_checklist: List[Dict[str, Any]] = Field(default_factory=list, description="30-day execution checklist")

    # Deal Intelligence
    best_outreach_channel: str = Field(default="email")
    estimated_deal_size: str = Field(default="Unknown")
    estimated_close_timeline: str = Field(default="Unknown")

    # Quality Metrics
    overall_confidence: int = Field(0, ge=0, le=100)
    data_quality_notes: str = Field(default="")

    # Raw Agent Outputs (Embedded for full audit trail)
    research_section: Dict[str, Any] = Field(default_factory=dict)
    memory_section: Dict[str, Any] = Field(default_factory=dict)
    strategy_section: Dict[str, Any] = Field(default_factory=dict)
    outreach_section: Dict[str, Any] = Field(default_factory=dict)
    review_section: Dict[str, Any] = Field(default_factory=dict)

    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Settings:
        name = "executive_reports"
        indexes = [
            [("owner_id", 1), ("lead_id", 1)],
            [("job_id", 1)],
            [("owner_id", 1), ("created_at", -1)],
            [("report_id", 1)],
        ]
